enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
rv-brand = "Piko Patches"

[Twitter]
build-mode = "apk"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
